name = "shortlink-worker"
main = "worker.js"
compatibility_date = "2024-11-12"

[[kv_namespaces]]
binding = "LINKS_KV"
id = "your_kv_namespace_id"

[triggers]
crons = ["0 0 * * *"] # 每天自动执行 scheduled()
