name = "shortlink-worker"
main = "worker.js"
compatibility_date = "2024-11-12"

[[kv_namespaces]]
binding = "LINKS_KV"
id = "717512fbc55f4486ac9ad03307080ecb"

[triggers]
crons = ["0 0 * * *"] # 每天自动执行 scheduled()
